# Product.create!([
#   {name: "The Elder Wand", description: "The most powerful wand in existence.", price: "350.0", image_url: "https://vignette.wikia.nocookie.net/harrypotter/images/5/59/Elder_Wand.png/revision/latest?cb=20161128051519"},
#   {name: "Sonic Screwdriver", description: "The Doctor's sciencey magic wand to get out of tight spots. Note: does not work on wood", price: "9.81", image_url: "https://pm1.narvii.com/5769/02c43bae28d966f64972126eea7354ce368aa8f2_hq.jpg"},
#   {name: "Buffy Box Set", description: "The complete series of Buffy", price: "75.0", image_url: "https://images-na.ssl-images-amazon.com/images/I/81WoIZbOHvL._SX466_.jpg"},
#   {name: "Portal Gun", description: "A gun used to create portals to cake", price: "500.0", image_url: "https://img1.cgtrader.com/items/783278/bc7c670a80/large/portal-gun-3d-model-obj-fbx-stl-sldprt-sldasm-slddrw-mtl.jpg"},
#   {name: "Geralt of Rivia", description: "The White Wolf from Kaer Morhen", price: "125.0", image_url: "https://cdn11.bigcommerce.com/s-0kvv9/images/stencil/1280x1280/products/179680/257697/witchergeraltgrandusine__31874.1513890076.jpg?c=2"},
#   {name: "Godzilla (2019)", description: "The King of the Monsters", price: "95.0", image_url: "https://www.fanboycollectibles.com/images/Monster%20Arts%20-%20Godzilla%20KoM%200001.jpg"},
#   {name: "Hitchhiker's Guide to the Galaxy", description: "In many of the more relaxed civilizations on the Outer Eastern Rim of the Galaxy, the Hitch-Hiker's Guide has already supplanted the great Encyclopaedia Galactica as the standard repository of all knowledge and wisdom, for though it has many omissions and contains much that is apocryphal, or at least wildly inaccurate, it scores over the older, more pedestrian work in two important respects. First, it is slightly cheaper; and secondly it has the words DON'T PANIC inscribed in large friendly letters on its cover.", price: "42.0", image_url: "https://images-na.ssl-images-amazon.com/images/I/81XSN3hA5gL.jpg"},
#   {name: "Lightsaber", description: "Part laser, part samurai sword, all awesome. The lightsaber is an elegant weapon for a more civilized age, not nearly as clumsy as a blaster", price: "275.0", image_url: "http://25.media.tumblr.com/d2456964024018fd930338c099371104/tumblr_n2m73lTx2Q1svn82uo1_400.gif"},
#   {name: "Space Cowboy Laser Gun", description: "This weapon has no other description than, Shiny!", price: "172.5", image_url: "https://medias.spotern.com/spots/w640/175205-1546551845.jpg"}
# ])